.TH "include/UI/button.hh" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/UI/button.hh
.SH SYNOPSIS
.br
.PP
\fR#include 'SDL\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbutton\fP"
.br
.RI "Class for button UI elements\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
