.TH "include/scenes/explorer.hh" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/scenes/explorer.hh
.SH SYNOPSIS
.br
.PP
\fR#include 'scene\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBexplorer_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
