.TH "include/game.hh" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/game.hh
.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include 'SDL\&.h'\fP
.br
\fR#include 'SDL_mixer\&.h'\fP
.br
\fR#include 'SDL_ttf\&.h'\fP
.br
\fR#include 'enum\&.hh'\fP
.br
\fR#include 'wm\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgame\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
