.TH "src/game/gameplay.cc" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/gameplay.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'enum\&.hh'\fP
.br
\fR#include 'game\&.hh'\fP
.br
\fR#include 'wm\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBchangeScene\fP (const std::pair< \fBscenes\fP, \fBsceneData\fP > &sceneChangeData, \fBwm\fP &winMan)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void changeScene (const std::pair< \fBscenes\fP, \fBsceneData\fP > & sceneChangeData, \fBwm\fP & winMan)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
