.TH "src/game/game.cc" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/game.cc
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./include/game\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwmInitData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBwmInit\fP (void *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int wmInit (void * data)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
