.TH "src/scenes/init.cc" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scenes/init.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'scenes/init\&.hh'\fP
.br
\fR#include 'SDL_image\&.h'\fP
.br
\fR#include 'game\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
