.TH "include/scenes/init.hh" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/scenes/init.hh
.SH SYNOPSIS
.br
.PP
\fR#include 'scene\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBintro_t\fP"
.br
.ti -1c
.RI "class \fBintro_t::slide\fP"
.br
.RI "Contains all the information required for a functional slideshow\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
