.TH "intro_t::slide" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
intro_t::slide \- Contains all the information required for a functional slideshow\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <init\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBslide\fP (size_t _fadeIn, size_t _fadeOut, size_t _duration, SDL_Texture *_texture, SDL_Rect _dest={}, bool \fBskippable\fP=true)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBfadeIn\fP"
.br
.ti -1c
.RI "size_t \fBduration\fP"
.br
.ti -1c
.RI "size_t \fBfadeOut\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtexture\fP"
.br
.ti -1c
.RI "SDL_Rect \fBdest\fP"
.br
.ti -1c
.RI "bool \fBskippable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains all the information required for a functional slideshow\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "intro_t::slide::slide (size_t _fadeIn, size_t _fadeOut, size_t _duration, SDL_Texture * _texture, SDL_Rect _dest = \fR{}\fP, bool skippable = \fRtrue\fP)"

.SH "Member Data Documentation"
.PP 
.SS "SDL_Rect intro_t::slide::dest"

.SS "size_t intro_t::slide::duration"

.SS "size_t intro_t::slide::fadeIn"

.SS "size_t intro_t::slide::fadeOut"

.SS "bool intro_t::slide::skippable"

.SS "SDL_Texture* intro_t::slide::texture"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
