.TH "src/main.cc" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cc
.SH SYNOPSIS
.br
.PP
\fR#include 'game\&.hh'\fP
.br
\fR#include 'pch\&.hh'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBskipIntro\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define skipIntro"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
