.TH "src/scenes/scene.cc" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scenes/scene.cc
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./include/scenes/scene\&.hh'\fP
.br
\fR#include '\&.\&./\&.\&./include/game\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
