.TH "shitcord_t" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shitcord_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shitcord\&.hh>\fP
.PP
Inherits \fBscene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshitcord_t\fP (const \fBgame\fP *\fBcontext\fP)"
.br
.RI "Construct a new shitcord t object\&. "
.ti -1c
.RI "\fB~shitcord_t\fP ()"
.br
.RI "Destroy the shitcord t object\&. "
.ti -1c
.RI "std::pair< \fBscenes\fP, \fBsceneData\fP > \fBupdate\fP () override"
.br
.RI "Update logic for shitcord\&. "
.ti -1c
.RI "void \fBrender\fP () override"
.br
.RI "Renders menu, and messages\&. "
.ti -1c
.RI "std::pair< \fBscenes\fP, \fBsceneData\fP > \fBhandle\fP (const SDL_Event &event) override"
.br
.RI "Handles hovers\&. "
.ti -1c
.RI "SDL_Texture * \fBgenerateOptions\fP (const std::array< std::string, 3 > options)"
.br
.RI "Generates the option texture from the surface\&. "
.in -1c

Public Member Functions inherited from \fBscene\fP
.in +1c
.ti -1c
.RI "SDL_Texture * \fBloadTexture\fP (const char *path)"
.br
.RI "Loads texture based on path\&. "
.ti -1c
.RI "\fBscene\fP (const \fBgame\fP *gameContext)"
.br
.RI "Construct a new scene object\&. "
.ti -1c
.RI "virtual \fB~scene\fP ()"
.br
.RI "Destroy the scene object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_Texture * \fBbackground\fP"
.br
.in -1c

Public Attributes inherited from \fBscene\fP
.in +1c
.ti -1c
.RI "const \fBgame\fP * \fBcontext\fP"
.br
.RI "Game context\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "shitcord_t::shitcord_t (const \fBgame\fP * context)"

.PP
Construct a new shitcord t object\&. Called only once when WM is initialised

.PP
\fBParameters\fP
.RS 4
\fIcontext\fP game context 
.RE
.PP

.SS "shitcord_t::~shitcord_t ()"

.PP
Destroy the shitcord t object\&. Called only when the wm is destroyed 
.SH "Member Function Documentation"
.PP 
.SS "SDL_Texture * shitcord_t::generateOptions (const std::array< std::string, 3 > options)"

.PP
Generates the option texture from the surface\&. 
.PP
\fBParameters\fP
.RS 4
\fIoptions\fP Options to be enumerated 
.RE
.PP
\fBReturns\fP
.RS 4
SDL_Texture* Texture, upscaled by a factor of 2\&. 
.RE
.PP

.SS "std::pair< \fBscenes\fP, \fBsceneData\fP > shitcord_t::handle (const SDL_Event & event)\fR [override]\fP, \fR [virtual]\fP"

.PP
Handles hovers\&. 
.PP
\fBParameters\fP
.RS 4
\fIevent\fP Event to be handled 
.RE
.PP
\fBReturns\fP
.RS 4
std::pair<scenes, sceneData>Returns the scene to be changed to, and the data that scene should contain 
.RE
.PP

.PP
Implements \fBscene\fP\&.
.SS "void shitcord_t::render ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Renders menu, and messages\&. 
.PP
Implements \fBscene\fP\&.
.SS "std::pair< \fBscenes\fP, \fBsceneData\fP > shitcord_t::update ()\fR [override]\fP, \fR [virtual]\fP"

.PP
Update logic for shitcord\&. Probably does the message appearing

.PP
\fBReturns\fP
.RS 4
std::pair<scenes, sceneData> Returns the scene to be changed to, and the data that scene should contain 
.RE
.PP

.PP
Implements \fBscene\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "SDL_Texture* shitcord_t::background"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
