.TH "src/scenes Directory Reference" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/scenes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBexplorer\&.cc\fP"
.br
.ti -1c
.RI "file \fBinit\&.cc\fP"
.br
.ti -1c
.RI "file \fBnotepad\&.cc\fP"
.br
.ti -1c
.RI "file \fBscene\&.cc\fP"
.br
.in -1c
