.TH "src/game/wm.cc" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game/wm.cc
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./\&.\&./include/wm\&.hh'\fP
.br
\fR#include '\&.\&./\&.\&./include/game\&.hh'\fP
.br
\fR#include '\&.\&./\&.\&./include/scenes/explorer\&.hh'\fP
.br
\fR#include '\&.\&./\&.\&./include/scenes/init\&.hh'\fP
.br
\fR#include '\&.\&./\&.\&./include/scenes/notepad\&.hh'\fP
.br
\fR#include '\&.\&./\&.\&./include/scenes/pause\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
