.TH "include/wm.hh" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/wm.hh
.SH SYNOPSIS
.br
.PP
\fR#include 'enum\&.hh'\fP
.br
\fR#include 'pch\&.hh'\fP
.br
\fR#include 'scenes/explorer\&.hh'\fP
.br
\fR#include 'scenes/init\&.hh'\fP
.br
\fR#include 'scenes/notepad\&.hh'\fP
.br
\fR#include 'scenes/pause\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBwm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
