.TH "wmInitData" 3 "Version 0.1.0" "Game" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wmInitData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwmInitData\fP (\fBwm\fP *_winMan, \fBgame\fP *_context, SDL_mutex *_mutex)"
.br
.ti -1c
.RI "\fB~wmInitData\fP ()"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwm\fP * \fBwinMan\fP"
.br
.ti -1c
.RI "\fBgame\fP * \fBcontext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "wmInitData::wmInitData (\fBwm\fP * _winMan, \fBgame\fP * _context, SDL_mutex * _mutex)\fR [inline]\fP"

.SS "wmInitData::~wmInitData ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void wmInitData::lock ()\fR [inline]\fP"

.SS "void wmInitData::unlock ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBgame\fP* wmInitData::context"

.SS "\fBwm\fP* wmInitData::winMan"


.SH "Author"
.PP 
Generated automatically by Doxygen for Game from the source code\&.
